### ISSUE TITLE
feat: nominate new start member

### ISSUE THREAD

**Issue by thuongtruong1009** [CURAJ-Open-Source-Community/Support#27]
### Name

Tran Nguyen Thuong Truong

### What you expect from the community?

Currently, I learning front-end.
I want to learn more and more about open-source code.
Hope to cooperate with you in the future.
Thank you!

**Comment by subastianSk** [comment]
Can you share knowledge, I also want to learn more front-end

**Comment by thuongtruong1009** [comment]
> 

i learning on Youtube, it is free and effective
